# Generated by Django 3.1 on 2020-10-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CraigsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Search'},
        ),
    ]
